### ISSUE TITLE
reserves value in reportbody

### ISSUE THREAD

**Issue by Syrrianyl** [Tkael/EliteDangerousDataProvider#51]
I have a very strange error with the proposition of script made for description of rings.
reportbody.reserves is always empty, and i don't know if it's only me.
I try to look how it work and i think that in "_**Body scanned**_" we work with _**BodyScannedEvent.cs**_, and in "_**Body report**_", we work more with _**DataProviderServices.cs**_
For exemple, to know if the body is Icy or metalic, we use _`reportbody.planettype`_ and not the **`.bodyclass`** of the event description.
It look like too complex for me to change all of that, so i go in easy way.
In "_**Body scanned**_"  I add a line:
`{SetState('Qual_Reserve', event.reserves)}`
and I try to call back with: {state.Qual_Reserve} and it also don't work.
I try again with my {GetState('Qual_Reserve)} and like that I retreive the event.reserves (very strange)

the reserves string are the raw fron edname, so:
- DepletedResources
- LowResources
- CommonResources
- MajorResources
- PristineResources

**Comment by Tkael** [comment]
Odd... it's working for me. All I have to do is type '{event.reserves}' in the Body scanned script and it returns 'PristineResources'.
Can you post a simplified version of your script so that we can test if we have the same problem? And can you post a copy of the journal event you are using for your test?

**Comment by Syrrianyl** [comment]
I restart with your source code from today, not mine, to be sure that i don't create error in the code.

To be fonctionnal, i make that for the rings in "_Body report_":

```
{set QualityRing to event.reserves}
{set NbreRing to len(event.rings)}
{if NbreRing > 0:
  with
        {if find(QualityRing , "Pristine") >= 0:
            pristine
        |elif find(QualityRing , "Major") >= 0:
            a {OneOf("rich", "high")} {OneOf("concentrations", "levels", "reserves")} of material in its
        }
 
        {set ringcomposition to []}
        {for Ring in reportbody.rings:
           {set ringcomposition to cat(ringcomposition, [Ring.composition])}
        }
        {if len(ringcomposition)= 1:
            {ringcomposition[0]}
        |elif len(ringcomposition) = 2:
            {ringcomposition[0]} and {ringcomposition[1]}
        |elif len(ringcomposition) > 2:
            {set cur to 0}
            {while cur < len(reportbody.rings):
                {if cur = 0:
                    {ringcomposition[cur]}
                |elif cur < len(ringcomposition) - 1:
                    , {ringcomposition[cur]}    
                |else:
                    , and {ringcomposition[cur]}
                }
                {set cur to cur + 1}
            }
        }
  {if NbreRing > 1: rings
  |else: ring}...
    }
```

I will try tomorrow in some other places because I find only pristine (and it is also pristine in the game log)
